# Generated by Django 3.0 on 2021-08-12 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techdb', '0002_auto_20210809_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(blank=True, null=True, verbose_name='Расстояние')),
                ('priority', models.TextField(blank=True, null=True, verbose_name='Приоритет')),
                ('type_hardware', models.TextField(blank=True, null=True, verbose_name='Тип аппаратной')),
                ('title', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='techdb.Site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
                'ordering': ['title'],
            },
        ),
    ]
