# Generated by Django 3.0 on 2021-08-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techdb', '0003_sitecommon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitecommon',
            options={'ordering': ['title'], 'verbose_name': 'Сайт', 'verbose_name_plural': 'Сайты_общая'},
        ),
    ]
