# Generated by Django 3.0 on 2021-08-13 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techdb', '0004_auto_20210812_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.TextField(blank=True, null=True, verbose_name='Приоритет')),
                ('serial_number', models.TextField(blank=True, null=True, verbose_name='Тип аппаратной')),
                ('title', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='techdb.Site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты_оборудование',
                'ordering': ['title'],
            },
        ),
    ]
