# Generated by Django 3.0 on 2021-08-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techdb', '0006_auto_20210818_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteequipment',
            options={'ordering': ['device'], 'verbose_name': 'Сайт', 'verbose_name_plural': 'Сайты_оборудование'},
        ),
        migrations.CreateModel(
            name='SiteBatteries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_of_voltage', models.TextField(blank=True, null=True, verbose_name='Система питания')),
                ('num_of_rect', models.IntegerField(blank=True, null=True, verbose_name='Количество выпрямителей')),
                ('battery_type', models.TextField(blank=True, null=True, verbose_name='Тип АКБ')),
                ('battery_num', models.IntegerField(blank=True, null=True, verbose_name='Количество АКБ')),
                ('battery_cap', models.IntegerField(blank=True, null=True, verbose_name='Емкость АКБ')),
                ('battery_date', models.DateField(blank=True, null=True, verbose_name='Дата установки АКБ')),
                ('title', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='techdb.Site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты_АКБ',
                'ordering': ['title'],
            },
        ),
    ]
