# Generated by Django 3.0 on 2021-08-24 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techdb', '0007_auto_20210824_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRRL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radiolink', models.TextField(blank=True, null=True, verbose_name='Направление РРЛ')),
                ('type_rrl', models.TextField(blank=True, null=True, verbose_name='Тип оборудования')),
                ('ip_access', models.TextField(blank=True, null=True, verbose_name='IP адрес')),
                ('title', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='techdb.Site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты_РРЛ',
                'ordering': ['radiolink'],
            },
        ),
    ]
