# Generated by Django 3.1.13 on 2021-12-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techdb', '0011_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteQuazar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(blank=True, null=True, verbose_name='Локация')),
                ('access', models.TextField(blank=True, null=True, verbose_name='Доступ')),
                ('keys', models.TextField(blank=True, null=True, verbose_name='Ключи')),
                ('energy', models.TextField(blank=True, null=True, verbose_name='Электроснабжение')),
                ('other', models.TextField(blank=True, null=True, verbose_name='Прочее')),
                ('title', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='techdb.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты_Квазар',
                'ordering': ['title'],
            },
        ),
    ]
