# Generated by Django 3.1.13 on 2022-09-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techdb', '0012_sitequazar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Район')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'телефон',
                'verbose_name_plural': 'Телефоны сетей',
                'ordering': ['title'],
            },
        ),
    ]
