# Generated by Django 3.1.13 on 2022-10-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techdb', '0013_phonebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyShedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата дежурства')),
                ('duty', models.TextField(blank=True, null=True, verbose_name='Дежурный')),
                ('duty_add', models.TextField(blank=True, null=True, verbose_name='Группа дежурного')),
                ('support', models.TextField(blank=True, null=True, verbose_name='Поддержка')),
                ('support_add', models.TextField(blank=True, null=True, verbose_name='Группа поддержки')),
            ],
            options={
                'verbose_name': 'дежурный',
                'verbose_name_plural': 'Дежурные',
                'ordering': ['date'],
            },
        ),
    ]
